import type { Metadata } from "next";

import "./globals.css";

import { Audiowide } from "next/font/google";

const AudioW = Audiowide({
  weight: '400',
  subsets: ["latin"],
});

import Logo from "@/Components/Logo";
import Navigation from "@/Components/Navigation";
import Cta from "@/Components/Cta";

const nItems = [
  {label: "Home", href: "/"},
  {label: "Services", href: "/services"},
  {label: "About", href:"/about"},
  {label: "Contact", href: "/contact"},
]


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header className="flex flex-row items-center gap-15">
        <div className="logo-container">
          <Logo text="206CE" imagePath="/logo180.png" size={100} />
        </div>
        <Navigation items={nItems} itemClassName="btn" />
      </header>
      <body className={`${AudioW.className} antialiased`}>{children}</body>
    </html>
  );
}
